### ISSUE TITLE
Compatibility with other composer/semver major versions

### ISSUE THREAD

**Issue by fjgarlin** [requtize/semver-converter#2]
It currently requires `"composer/semver": "~1.4"`, but the library is already at major version 3. It would be awesome to support this as otherwise the package cannot be installed in that setup.

**Comment by fjgarlin** [comment]
`"composer/semver": "^3.2"` should do.

**Comment by adambanaszkiewicz** [comment]
I've done the merge. There is a 0.4.0 release version with Your changes.
